set nocompatible " Enables no-vi features
filetype off
set rtp+=$DOTDIR/.vim
set viminfo+=n$DOTDIR/.vim/viminfo
set shell=/bin/zsh

" --Vundle--
"Vundle bootstrap
if !filereadable($DOTDIR . '/.vim/bundle/Vundle.vim/.git/config') && confirm("Clone Vundle?","Y\nn") == 1
    exec '!git clone https://github.com/gmarik/Vundle.vim $DOTDIR/.vim/bundle/Vundle.vim/'
    echo "Run :PluginInstall in vim"
endif

set rtp+=$DOTDIR/.vim/bundle/Vundle.vim " set the runtime path to include Vundle
call vundle#begin($DOTDIR."/.vim/bundle")

" Let Vundle manange itself:
Plugin 'VundleVim/Vundle.vim'

" Markdown plugin & tabular dependency
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

" Filetree plugin
Plugin 'preservim/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" YouCompleteMe
Plugin 'valloric/youcompleteme'

" Surround plugin
Plugin 'tpope/vim-surround'

" Commentary plugin
Plugin 'tpope/vim-commentary'

" Go support
Plugin 'fatih/vim-go', { 'do': ':GoInstallBinaries' }

" Nice line on the bottom of the screen
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Color schema
Plugin 'dracula/vim',{'name':'dracula'}

" Fuzzy find
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plugin 'junegunn/fzf.vim'

" Smooth scrolling
Plugin 'terryma/vim-smooth-scroll'

" Sign Column git diff
Plugin 'airblade/vim-gitgutter'

call vundle#end()
" ---------

filetype plugin on
syntax on "Syntax highlighting
set encoding=utf-8

" Set color-scheme
colorscheme dracula
highlight Normal ctermbg=None
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1

" Configure air-line
let g:airline_theme='dracula'

" Reset space key as leader
let mapleader = " "

set number relativenumber " Show current line-number & relative #s
set noerrorbells

" Configure tabs as 2 spaces
set expandtab
set shiftwidth=2
set softtabstop=2 tabstop=2
set smartindent

" Default to nowrap, toggle with Space+w
set nowrap
nnoremap <leader>w :set wrap!<CR>

" Configure search
set ignorecase " Ignore case when searching
set smartcase " ...unless something in search is capitalized
set incsearch " Highlight search matches as you type

" Use an undodir to allow for undo after closing vim
set nobackup
set undodir=$DOTDIR/.vim/undodir
set undofile

" Set a dark column at col 120
set colorcolumn=121
highlight ColorColumn ctermbg=0 guibg=lightgrey

" Yank and paste to/from normal clipboard
set clipboard^=unnamed,unnamedplus

" Add spellcheck
nnoremap <leader>z 1z=
nnoremap <leader>s :set spell! spelllang=en_us<CR>

" Set highlight on search
set hlsearch
nnoremap <leader>h :noh<CR>

" Markdown Settings
let g:vim_markdown_folding_disabled = 1
set conceallevel=2
set linebreak
" formatoptions+=rt

" Toggle Nerdtree
nnoremap <leader>t :NERDTreeToggle<CR>
nnoremap <leader>T :NERDTreeFind<CR>
let NERDTreeShowHidden=1

" Navigate tabs w/ <C-{jk}>
nnoremap <C-k> :tabprev<CR>
nnoremap <C-j> :tabnext<CR>
nnoremap <C-n> :tabnew<CR>

" Navigate windows w/ <C-{hl}>
map <C-l> :wincmd l<CR>
map <C-h> :wincmd h<CR>

"" Better movement
map H ^
map L $

" Smooth scrolling
noremap <silent> <C-u> :call smooth_scroll#up(&scroll, 0, 2)<CR>
noremap <silent> <C-d> :call smooth_scroll#down(&scroll, 0, 2)<CR>
noremap <silent> <C-b> :call smooth_scroll#up(&scroll*2, 0, 4)<CR>
noremap <silent> <C-f> :call smooth_scroll#down(&scroll*2, 0, 4)<CR>

"" Better indenting
nmap >> <Nop>
nmap << <Nop>
vmap >> <Nop>
vmap << <Nop>

nnoremap <Tab>    >>
nnoremap <S-Tab>  <<
vnoremap <Tab>    >><Esc>gv
vnoremap <S-Tab>  <<<Esc>gv

" Pair braces
inoremap <> <><Left>
inoremap () ()<Left>
inoremap {} {}<Left>
inoremap [] []<Left>
inoremap "" ""<Left>
inoremap '' ''<Left>
inoremap `` ``<Left>

" fzf remappings
nnoremap <silent> <leader>o :Files<CR>
nnoremap <silent> <leader>f :Rg<CR>

" delete without yanking
nnoremap <leader>d "_d
vnoremap <leader>d "_d

" replace currently selected text with default register
" without yanking it
vnoremap <leader>p "_dP

