set nocompatible " Enables no-vi features
filetype off
set rtp+=$DOTDIR/.vim
set viminfo+=n$DOTDIR/.vim/viminfo
set shell=/bin/zsh

" --Vundle--
"Vundle bootstrap
if !filereadable($DOTDIR . '/.vim/bundle/Vundle.vim/.git/config') && confirm("Clone Vundle?","Y\nn") == 1
    exec '!git clone https://github.com/gmarik/Vundle.vim $DOTDIR/.vim/bundle/Vundle.vim/'
    echo "Run :PluginInstall in vim"
endif

set rtp+=$DOTDIR/.vim/bundle/Vundle.vim " set the runtime path to include Vundle
call vundle#begin($DOTDIR."/.vim/bundle")

" Let Vundle manange itself:
Plugin 'VundleVim/Vundle.vim'

" Markdown plugin & tabular dependency
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

" Filetree plugin
Plugin 'preservim/nerdtree'

" YouCompleteMe
Plugin 'valloric/youcompleteme'

" Surround plugin
Plugin 'tpope/vim-surround'

" Go support
Plugin 'fatih/vim-go', { 'do': ':GoInstallBinaries' }

" Nice line on the bottom of the screen
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Color schema
Plugin 'dracula/vim',{'name':'dracula'}

call vundle#end()
" ---------

filetype plugin indent on " Filetype auto-detection
syntax on "Syntax highlighting
set encoding=utf-8

" Set color-scheme
let g:dracula_italic = 0
colorscheme dracula
highlight Normal ctermbg=None

" Configure air-line
let g:airline_theme='dracula'

" Reset space key as leader
let mapleader = " "

set number relativenumber " Show current line-number & relative #s
set noerrorbells

" Configure tabs as 2 spaces
set expandtab
set shiftwidth=2
set softtabstop=2 tabstop=2
set smartindent

" Default to nowrap, toggle with Space+w
set nowrap
nnoremap <leader>w :set wrap!<CR>

" Configure search
set ignorecase " Ignore case when searching
set smartcase " ...unless something in search is capitalized
set incsearch " Highlight search matches as you type

" Use an undodir to allow for undo after closing vim
set nobackup
set undodir=$DOTDIR/.vim/undodir
set undofile

" Set a dark column at col 120
set colorcolumn=121
highlight ColorColumn ctermbg=0 guibg=lightgrey

" Yank and paste to/from normal clipboard
set clipboard^=unnamed,unnamedplus

" Add spellcheck
nnoremap <leader>f 1z=
nnoremap <leader>s :set spell! spelllang=en_us

" Set highlight on search
set hlsearch
nnoremap <leader>h :noh<CR>

" Markdown Settings
let g:vim_markdown_folding_disabled = 1
set conceallevel=2
set linebreak
" formatoptions+=rt

" Toggle Nerdtree
nnoremap <leader>t :NERDTreeToggle

" Navigate tabs w/ <C-{jk}>
nnoremap <C-k> :tabprev<CR>
nnoremap <C-j> :tabnext<CR>
nnoremap <C-n> :tabnew<CR>

" Navigate windows w/ <C-{hl}>
map <C-l> :wincmd l<CR>
map <C-h> :wincmd h<CR>

"" Better movement
map K <C-u>
map J <C-d>
map H ^
map L $

"" Better indenting
nmap >> <Nop>
nmap << <Nop>
vmap >> <Nop>
vmap << <Nop>

nnoremap <Tab>    >>
nnoremap <S-Tab>  <<
vnoremap <Tab>    >><Esc>gv
vnoremap <S-Tab>  <<<Esc>gv

" Pair braces
inoremap <> <><Left>
inoremap () ()<Left>
inoremap {} {}<Left>
inoremap [] []<Left>
inoremap "" ""<Left>
inoremap '' ''<Left>
inoremap `` ``<Left>

